### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by friedger** [xgouchet/Stanley#12]
I am interested in re-using your code for building an open database of manifest data and eventually providing dependency management between apps that was started here: https://github.com/openintents/openintents/tree/master/dependencymanager

What is the license of your code?

**Comment by xgouchet** [comment]
It's true that I didn't add a License file, but mos of my work is under MIT License, I gues this one will be also. 
If you want you can mention that you're basing your new code on this project, and include my name. 

Cheers :)
