### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by ShalokShalom** [xgouchet/Stanley#16]
The app description in the F-Droid app shop says "Developpers"

**Comment by mueller-ma** [comment]
It also says "informations".
@xgouchet You may want to move the f-droid description into this repo, so you can add screenshots and the description can be localized.
https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/

**Comment by ShalokShalom** [comment]
It still says developpers here in Github

**Comment by xgouchet** [comment]
Fixed

**Comment by mueller-ma** [comment]
Can you add some screenshots to the fastlane metadata? It's pretty easy for you to add these information as you already provide metadata in your repo for F-Droid. Please have a look at [this example](https://github.com/Freeyourgadget/Gadgetbridge/tree/master/fastlane/metadata/android) or at the [F-Droid docs](https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/#in-the-apps-source-repository) or [fastlane docs](https://github.com/fastlane/fastlane/blob/2.28.7/supply/README.md#images-and-screenshots).
