### ISSUE TITLE
Launch icon on app list item.

### ISSUE THREAD

**Issue by bizzguy** [xgouchet/Stanley#32]
I'd like to have a icon on each of the items on the app list that would allow the app to be started directly from the app list, instead of having to go to the app detail and launching the app there.  

I'd be very interested in creating a pull request for this if you could give me a little guidance on how to assign the listener.  I could use the same launch icon that is on the detail screen.

And also - great app - thanks for creating it.

**Comment by xgouchet** [comment]
This is an interesting feature. One of the issue is that a single application could have more than one "main" activity, and so this feature is not trivial. But I'll keep it in mind for the next version.
