### ISSUE TITLE
Project no longer building under current stable version of Android Studio (3.3.2)

### ISSUE THREAD

**Issue by bizzguy** [xgouchet/Stanley#33]
When building the project under the current stable version of Android Studio the build fails with the following error:

ERROR: No toolchains found in the NDK toolchains folder for ABI with prefix: mips64el-linux-android
This version of the NDK may be incompatible with the Android Gradle plugin version 3.0 or older.
Please use plugin version 3.1 or newer.
Upgrade plugin to version 3.3.2 and sync project

**Comment by xgouchet** [comment]
I'll try and investigate and fix that, thanks for reporting it.
