### ISSUE TITLE
Support Unsigned APKs

### ISSUE THREAD

**Issue by mwarning** [xgouchet/Stanley#36]
If an APK is unsigned Stanley only shows ""Error: packageInfo must not be null".

(I've run into this problem with these apks: https://github.com/mwarning/trigger/releases/tag/v1.9.0)

**Comment by mwarning** [comment]
Do unsigned packages do not have packageInfo? Or is it just not supported?

**Comment by xgouchet** [comment]
They'll be supported in the next version of the app. It's just that when fetching the package info I should not request to get signatures

**Comment by mwarning** [comment]
Ah, I see. Thanks for heads up.
