### ISSUE TITLE
The 3 dots displays a white window; crash

### ISSUE THREAD

**Issue by yhutoo** [xgouchet/Stanley#40]
v2.6: the 3 dots displays a white window instead of the menu; cliking blindly in some space works; clicking on another blind space the app crashes.
ASUS ZenFone 3, Android 6.0.1
Thks, best.

**Comment by Astuceman** [comment]
Almost same issue
When I click on "About" it crash
Android 10 | SM-970F (Galaxy S10e)

**Comment by Disqu3-mirOir-qt** [comment]
same for me

**Comment by Gitoffthelawn** [comment]
Same here. Samsung device. For more details, just ask.

**Comment by ygsk10** [comment]
Same here 
Android 10 | blueline

**Comment by ghost** [comment]
it seems menus appear when in "Dark Mode" , while the "about" caused crashing.

**Comment by mmm4m5m** [comment]
Dots and sort menu - both are white font, white background.
Checked with android 7, 8, 9. 

@ygsk10 - How to enter "dark mode"?

**Comment by ghost** [comment]
> Dots and sort menu - both are white font, white background.
> Checked with android 7, 8, 9.
> 
> @ygsk10 - How to enter "dark mode"?

For me >> Settings - Accessibility - Dark Theme
I am not sure if some ROMs have this feature.

**Comment by RoestVrijStaal** [comment]
Why is this issue closed?

Switching OS themes isn't a right solution when the app doesn't handle UI styling properly.

I'm not going to switch theme back and forth for 1 app 😒

**Comment by Gitoffthelawn** [comment]
@RoestVrijStaal This issue report is for a crash.  Are you experiencing a crash?  If so, please indicate.  If not, please open a new issue describing the issue you are experiencing and how to reproduce it.
