### ISSUE TITLE
Proprietary components in Stanley

### ISSUE THREAD

**Issue by IzzySoft** [xgouchet/Stanley#54]
I fear we have a problem. In Stanley, you're using the *Google Play OSS-Licenses* library (`com.google.android.gms.oss.licenses`), which unfortunately drags in some more GMS components – which F-Droid cannot accept. Seems like all versions so far are affected.

Can we convince you replacing that library by something else? I've collected a [short list](https://gitlab.com/snippets/1896503#license-dialogs) of potential candidates (if someone knows more, suggestions are welcome). Stanley using the MIT license would make [SimpleLicenseDisplay](https://github.com/MarcDonald/SimpleLicenseDisplay) the closest match, as that's also MIT licensed.

Any chance for that, @xgouchet? Would be a real pity had we to disable the app entirely at F-Droid. Would be great if the next release of Stanley could address this instead, and be available soon. Thanks in advance!

PS, disclosure: I'm one of the F-Droid maintainers. This issue surfaced when we did a scan of all APKs with another library scanner we didn't use in the past (we always check how we can improve :wink:).

**Comment by xgouchet** [comment]
Hello @IzzySoft , this actually is something that I did take care of a while back (in october if memory serves me well). But you're right I failed to make a release after that, I'll do so shortly. Thanks for taking this issue to maintainers of project, and thanks a lot for your work at F-Droid :)

**Comment by xgouchet** [comment]
As a follow up, I just tagged version [`v2.7`](https://github.com/xgouchet/Stanley/releases/tag/v2.7) which should trigger an update on Stanley in F-Droid.

**Comment by IzzySoft** [comment]
Thanks for your fast response, Xavier – that's awesome! And thanks for providing the fixed build quasi overnight :smiley:

That tackled, I'd disable all older builds once the new one shows up in our index, which should hopefully happen within a week. That meets our guidelines (having the builds breaking our inclusion criteria disabled) while keeping your app "alive" without interruption. Looking at my current workload (and pending details on the other affected apps), noone can argue "the delay" I'd say.
