### ISSUE TITLE
Wrong installation and update dates on Android 10 with Stanley 2.7

### ISSUE THREAD

**Issue by AtjonTV** [xgouchet/Stanley#61]
I just noticed that all dates shown by Stanley are 1st January 1970, regardless on when the app was installed or updated.

I first tried to clear caches without luck and then to reinstalled Stanley (2.7 / 19) via F-Droid but it didn't help:

![Screenshot_20211105_155414_fr xgouchet packageexplorer](https://user-images.githubusercontent.com/24845056/140531027-045b809b-5bff-4ac5-935a-5e4f0bb64e00.jpg)

Additional information:

```
Device: Huawei P40 Pro+
OS: Android 10
UI: EMUI 11.0.0.211 (EU Version)
GMS: No, but microG 0.2.22.212658 (no spoofing)
HMS: 6.2.0.302
```

**Comment by AtjonTV** [comment]
I just tried and confirmed this broken on a EMUI 10/Android 10 device. So at least it's not a EMUI 11 issue.

On this same device Stanley 2.6 worked flawless (besides the known crash bug for clicking About in the menu)

(Tested on Huawei P smart Z)

**Comment by AtjonTV** [comment]
So .. restoring Stanley 2.6 via Huawei Cloud I can confirm it working on both devices, showing the correct dates.

So this is a 2.7 issue, yet I don't know and can't confirm if this is broken on other Android versions. (All devices I have at hand run Android 10)

**Comment by AtjonTV** [comment]
Dates fall back to zero if null given:
https://github.com/xgouchet/Stanley/blob/e7affd633045f6d4811a0d12f23386bb776ab043/app/src/main/java/fr/xgouchet/packageexplorer/applist/AppViewModel.kt#L68

And here is the only place explicitly giving null:
https://github.com/xgouchet/Stanley/blob/e7affd633045f6d4811a0d12f23386bb776ab043/app/src/main/java/fr/xgouchet/packageexplorer/applist/AppListSource.kt#L29



Where I found this being changed: https://github.com/xgouchet/Stanley/commit/e7affd633045f6d4811a0d12f23386bb776ab043

**Comment by xgouchet** [comment]
Hi @AtjonTV thanks for raising this issue. I'll try and fix it soon, feel free to open a PR in the meantime.
