### ISSUE TITLE
[Bug/UI] Package name vertical overflow

### ISSUE THREAD

**Issue by dreamsyntax** [xgouchet/Stanley#66]
The package name (org.bromite.bromite in example) overflows vertically, where the text is not fully readable on some screens.

TODO:
* Adjust text size or shift height of bar to account for this

Example image:
![sample](https://user-images.githubusercontent.com/14857235/188768461-d9970e12-1037-4f32-9ca0-1c4e10aaa9d9.jpg)

**Comment by xgouchet** [comment]
Hi @dreamsyntax and thanks for reporting this. Indeed this is something that I'll try and fix in the future.

**Comment by ImnIrdst** [comment]
Hey, I've created a PR that fixes this issue. #75
